### ISSUE TITLE
Use scale3d/transform3d / trigger GPU acceleration

### ISSUE THREAD

**Issue by strarsis** [gre/kenburns-dom#1]
Wouldn't it improve performance using scale3d instead scale and transform3d instead transform because the CSS *3d transform values are GPU accelerated?
It would also possible forcing/triggering GPU acceleration by using some non-visual 3D transform on the same element.

**Comment by gre** [comment]
do you have reference of this? I'm not sure if this assumption is still true nowadays. wouldn't it be a limitation of the browser if scale3d() would be more performant than scale() ?

**Comment by strarsis** [comment]
Most articles about this topic are already 2-3 years old, but also I haven't found yet one that indicates browsers would use GPU acceleration all the time now.

Recent (enough?) resources:
- http://stackoverflow.com/questions/12643240/improving-css3-transition-performance
- https://www.sitepoint.com/introduction-to-hardware-acceleration-css-animations/

**Comment by gre** [comment]
ok yeah, I guess we can move to the *3d version then, do you want to provide a PR ? thanks

**Comment by strarsis** [comment]
I will have to test it first: https://github.com/gre/kenburns-dom/pull/2
